const OrderActionTypes = {
  PLACE_ORDER_START: 'PLACE_ORDER_START',
  PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS',
  PLACE_ORDER_FAILURE: 'PLACE_ORDER_FAILURE',
  GET_USER_ORDERS_START: 'GET_USER_ORDERS_START',
  GET_USER_ORDERS_SUCCESS: 'GET_USER_ORDERS_SUCCESS',
  GET_USER_ORDERS_FAILURE: 'GET_USER_ORDERS_FAILURE',
  CLEAR_USER_ORDERS: 'CLEAR_USER_ORDERS',
};

export default OrderActionTypes;
